name: miniaudio_dart_ffi
description: FFI implementation of the MiniaudioDart package.
version: 1.0.4
publish_to: none
repository: https://github.com/MichealReed/miniaudio_dart/tree/master/miniaudio_dart_ffi

#####

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  ffi: ^2.0.2
  miniaudio_dart_platform_interface:
    path: ../miniaudio_dart_platform_interface
  native_toolchain_cmake: ^0.0.6-dev.0

dev_dependencies:
  flutter_lints: ^2.0.1
  ffigen: ^18.0.0

#####

ffigen:
  name: MiniaudioDartFfiBindings
  description: Bindings for miniaudio_dart.h
  output: "lib/miniaudio_dart_ffi_bindings.dart"
  headers:
    entry-points:
      - "src/include/miniaudio_dart.h"
      - "src/include/engine.h"
      - "src/include/sound.h"
      - "src/include/record.h"
      - "src/include/generator.h"
      - "src/include/circular_buffer.h"
      - "src/include/silence_data_source.h"
      - "src/include/stream_player.h"
    include-directives:
      - "src/include/*.h"
      - "/usr/lib/clang/18/include/stdbool.h"
      - "/usr/lib/clang/18/include/stdint.h"
  preamble: |
    // ignore_for_file: camel_case_types
    // ignore_for_file: prefer_double_quotes
    // ignore_for_file: non_constant_identifier_names
    // ignore_for_file: constant_identifier_names
    // ignore_for_file: prefer_expression_function_bodies
    // ignore_for_file: sort_constructors_first
    // ignore_for_file: unused_element 
  llvm-path:
    - /usr/lib64/libclang.so
  compiler-opts:
    - -I/usr/lib/clang/18/include/
  ffi-native:
  silence-enum-warning: true

##
